import { mkdir, writeFile } from 'fs/promises'
import { dirname, join, parse } from 'path'
import type { ClassIR, FunctionIR, ModuleIR } from './ir.js'
import {
  dedupeStrings,
  pythonizeType,
  safePythonIdentifier,
} from './parserUtils.js'

function formatCommentList(label: string, values: readonly string[]): string[] {
  const normalized = dedupeStrings(values)
  if (normalized.length === 0) {
    return []
  }
  return [`# ${label}: ${normalized.join(', ')}`]
}

function renderParam(param: FunctionIR['params'][number]): string {
  const name = safePythonIdentifier(param.name, 'arg')
  const annotation = pythonizeType(param.annotation)
  return `${name}: ${annotation}`
}

function renderFunction(
  fn: FunctionIR,
  options: { indent: string; insideClass: boolean },
): string[] {
  const indent = options.indent
  const lines: string[] = []
  const functionName =
    fn.name === 'constructor'
      ? '__init__'
      : safePythonIdentifier(fn.name, 'generated_function')
  const params = fn.params
    .filter(param => !['this', 'self', 'cls'].includes(param.name))
    .map(renderParam)

  if (options.insideClass) {
    params.unshift('self')
  }

  const returns =
    functionName === '__init__' ? 'None' : pythonizeType(fn.returns)
  const prefix = fn.isAsync ? 'async ' : ''

  if (fn.decorators.length > 0) {
    lines.push(
      `${indent}# decorators: ${dedupeStrings(fn.decorators).join(', ')}`,
    )
  }
  if (!fn.isPublic) {
    lines.push(`${indent}# visibility: non-public`)
  }
  lines.push(`${indent}# qualified_name: ${fn.qualifiedName}`)
  lines.push(
    `${indent}# source_lines: ${fn.sourceLines.start}-${fn.sourceLines.end}`,
  )
  lines.push(...formatCommentList('calls', fn.calls).map(line => indent + line))
  lines.push(...formatCommentList('awaits', fn.awaits).map(line => indent + line))
  lines.push(...formatCommentList('raises', fn.raises).map(line => indent + line))
  lines.push(
    `${indent}${prefix}def ${functionName}(${params.join(', ')}) -> ${returns}:`,
  )
  lines.push(`${indent}    ...`)
  return lines
}

function renderClass(cls: ClassIR): string[] {
  const lines: string[] = []
  const className = safePythonIdentifier(cls.name, 'GeneratedClass')
  lines.push(`# class: ${cls.qualifiedName}`)
  lines.push(`# source_lines: ${cls.sourceLines.start}-${cls.sourceLines.end}`)
  lines.push(...formatCommentList('bases', cls.bases))
  lines.push(...formatCommentList('depends_on', cls.dependsOn))
  lines.push(`class ${className}:`)

  if (cls.methods.length === 0) {
    lines.push('    ...')
    return lines
  }

  const renderedMethods = cls.methods.flatMap((method, index) => [
    ...(index === 0 ? [] : ['']),
    ...renderFunction(method, { indent: '    ', insideClass: true }),
  ])
  lines.push(...renderedMethods)
  return lines
}

function renderModuleSkeleton(module: ModuleIR): string {
  const lines: string[] = [
    '# Auto-generated by Claude Code /index',
    `# source: ${module.relativePath}`,
    `# language: ${module.language}`,
    `# parse_mode: ${module.parseMode}`,
    ...formatCommentList('imports', module.imports),
    ...formatCommentList('exports', module.exports),
    ...module.notes.map(note => `# note: ${note}`),
    ...module.errors.map(error => `# error: ${error}`),
    '',
    'from __future__ import annotations',
    'from typing import Any',
    '',
  ]

  if (module.classes.length === 0 && module.functions.length === 0) {
    lines.push('...')
    return lines.join('\n') + '\n'
  }

  const body: string[] = []
  for (const cls of module.classes) {
    if (body.length > 0) {
      body.push('')
    }
    body.push(...renderClass(cls))
  }

  for (const fn of module.functions) {
    if (body.length > 0) {
      body.push('')
    }
    body.push(...renderFunction(fn, { indent: '', insideClass: false }))
  }

  return [...lines, ...body].join('\n') + '\n'
}

function getSkeletonRelativePath(
  relativePath: string,
  usedPaths: Set<string>,
): string {
  const parsed = parse(relativePath)
  let candidate = join(parsed.dir, `${parsed.name}.py`).replaceAll('\\', '/')
  if (!usedPaths.has(candidate)) {
    usedPaths.add(candidate)
    return candidate
  }

  const disambiguated = join(
    parsed.dir,
    `${parsed.name}__${parsed.base.replace(/[^A-Za-z0-9]+/g, '_')}.py`,
  ).replaceAll('\\', '/')
  usedPaths.add(disambiguated)
  return disambiguated
}

export async function emitSkeletonTree(
  modules: readonly ModuleIR[],
  outputDir: string,
): Promise<void> {
  const skeletonRoot = join(outputDir, 'skeleton')
  const usedPaths = new Set<string>()

  for (const module of modules) {
    const relativeTarget = getSkeletonRelativePath(module.relativePath, usedPaths)
    const targetPath = join(skeletonRoot, relativeTarget)
    await mkdir(dirname(targetPath), { recursive: true })
    await writeFile(targetPath, renderModuleSkeleton(module), 'utf8')
  }

  const overview = [
    '# Auto-generated by Claude Code /index',
    `# modules: ${modules.length}`,
    `# sources: ${modules.map(module => module.relativePath).slice(0, 20).join(', ')}`,
    '...',
    '',
  ].join('\n')
  await writeFile(join(skeletonRoot, '__root__.py'), overview, 'utf8')
}

