/**
 * Session state serializer and merger for the Context Compression Engine.
 *
 * - mergeExtractionResult: incrementally updates a SessionState from extracted atoms
 * - serializeToPython: renders the SessionState as a Python file (session_state.py)
 * - deserializeFromPython: (optional) rehydrates state from the Python output
 */

import {
  type Decision,
  DecisionStatus,
  type Constraint,
  type TaskRecord,
  type SessionState,
} from './models.js'
import type { ExtractionResult } from './extractors.js'

// ── Defaults ───────────────────────────────────────────────────────────────

const MAX_DECISIONS = 30
const MAX_CONSTRAINTS = 20
const MAX_TASKS = 15
const MAX_CODE_ANCHORS = 20
const MAX_ERROR_MEMORIES = 10

export function createEmptySessionState(): SessionState {
  return {
    primaryGoal: '',
    decisions: [],
    constraints: [],
    tasks: [],
    lastUpdatedTurn: 0,
  }
}

// ── State Merger ───────────────────────────────────────────────────────────

export function mergeExtractionResult(
  state: SessionState,
  result: ExtractionResult,
  turn: number,
): SessionState {
  const next: SessionState = {
    ...state,
    lastUpdatedTurn: turn,
    decisions: [...state.decisions],
    constraints: [...state.constraints],
    tasks: [...state.tasks],
  }

  // Goal update
  if (result.goalUpdate) {
    next.primaryGoal = result.goalUpdate
  }

  // Decisions — merge by topic
  for (const dec of result.decisions) {
    const existingIdx = next.decisions.findIndex(
      d => d.topic === dec.topic && d.status !== DecisionStatus.SUPERSEDED,
    )

    if (existingIdx >= 0) {
      if (dec.status === DecisionStatus.REJECTED) {
        next.decisions[existingIdx] = {
          ...next.decisions[existingIdx],
          status: DecisionStatus.SUPERSEDED,
        }
        next.decisions.push(dec)
      } else if (dec.status === DecisionStatus.ACCEPTED) {
        next.decisions[existingIdx] = {
          ...dec,
          alternativesRejected: [
            ...next.decisions[existingIdx].alternativesRejected,
            next.decisions[existingIdx].choice,
          ],
        }
      }
    } else {
      next.decisions.push(dec)
    }
  }

  // Constraints — deduplicate by rule
  for (const con of result.constraints) {
    const exists = next.constraints.some(
      c => c.rule === con.rule && c.isActive,
    )
    if (!exists) {
      next.constraints.push(con)
    }
  }

  // Tasks — apply updates
  for (const taskUpdate of result.tasks) {
    switch (taskUpdate.action) {
      case 'create':
        next.tasks.push({
          id: `task_${turn}_${next.tasks.length}`,
          description: taskUpdate.description,
          status: 'planned',
          completedSubtasks: [],
          remainingSubtasks: [],
          artifacts: [],
          turn,
        })
        break

      case 'complete': {
        const match = next.tasks.find(
          t =>
            t.status === 'in_progress' ||
            t.status === 'planned' ||
            t.description.toLowerCase().includes(taskUpdate.description.toLowerCase().slice(0, 20)),
        )
        if (match) {
          match.status = 'done'
          match.completedSubtasks.push(taskUpdate.description)
        }
        break
      }

      case 'block': {
        const blocked = next.tasks.find(
          t => t.status === 'in_progress' || t.status === 'planned',
        )
        if (blocked) {
          blocked.status = 'blocked'
        }
        break
      }
    }
  }

  // Trim to limits
  if (next.decisions.length > MAX_DECISIONS) {
    const active = next.decisions.filter(d => d.status !== DecisionStatus.SUPERSEDED)
    const superseded = next.decisions
      .filter(d => d.status === DecisionStatus.SUPERSEDED)
      .slice(-(MAX_DECISIONS - active.length))
    next.decisions = [...active, ...superseded].slice(-MAX_DECISIONS)
  }

  next.constraints = next.constraints.filter(c => c.isActive).slice(-MAX_CONSTRAINTS)
  next.tasks = next.tasks.slice(-MAX_TASKS)

  return next
}

// ── Python Serializer ──────────────────────────────────────────────────────

function pyStr(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `'${escaped}'`
}

function pyList(items: string[]): string {
  if (items.length === 0) return '[]'
  const quoted = items.map(i => pyStr(i))
  if (quoted.length <= 3) return `[${quoted.join(', ')}]`
  return `[${quoted.join(', ')}]`
}

export function serializeToPython(state: SessionState): string {
  const lines: string[] = []

  lines.push('# session_state.py  (auto-generated by context compressor)')
  lines.push('# ════════════════════════════════════════════════════════════════')
  lines.push('# COMPRESSED SESSION STATE')
  lines.push('# This file captures decisions, constraints, and task progress')
  lines.push('# from the conversation. Re-inject into Context on each turn.')
  lines.push('# ════════════════════════════════════════════════════════════════')
  lines.push('from __future__ import annotations')
  lines.push('from typing import Dict, List, Optional')
  lines.push('')
  lines.push('')

  // ── CurrentSession class ──
  lines.push('class CurrentSession:')
  lines.push(`    primary_goal = ${pyStr(state.primaryGoal || 'Not yet defined')}`)
  lines.push(`    last_updated_turn = ${state.lastUpdatedTurn}`)
  lines.push('')

  // ── Decisions ──
  lines.push('    class Decisions:')
  const activeDecisions = state.decisions.filter(
    d => d.status === DecisionStatus.ACCEPTED,
  )
  const rejectedDecisions = state.decisions.filter(
    d => d.status === DecisionStatus.REJECTED,
  )

  if (activeDecisions.length === 0 && rejectedDecisions.length === 0) {
    lines.push('        ...  # No decisions recorded yet')
  } else {
    for (const dec of activeDecisions) {
      const varName = toPythonVarName(dec.topic)
      const comment = dec.alternativesRejected.length > 0
        ? `  # rejected: ${dec.alternativesRejected.join(', ')}`
        : ''
      lines.push(`        ${varName} = ${pyStr(dec.choice)}${comment}`)
    }

    if (rejectedDecisions.length > 0) {
      lines.push('')
      lines.push('        # Explicitly rejected:')
      for (const dec of rejectedDecisions) {
        const varName = toPythonVarName(`rejected_${dec.topic}`)
        lines.push(`        ${varName} = ${pyList(dec.alternativesRejected)}`)
      }
    }
  }
  lines.push('')

  // ── Constraints ──
  lines.push('    class Constraints:')
  if (state.constraints.length === 0) {
    lines.push('        ...  # No constraints recorded yet')
  } else {
    for (const con of state.constraints) {
      const varName = toPythonVarName(`${con.category}_${con.id.slice(-6)}`)
      const severity = con.severity === 'hard' ? '# MUST follow' : '# Recommended'
      lines.push(`        ${varName} = ${pyStr(con.rule)}  ${severity}`)
    }
  }
  lines.push('')

  // ── Tasks ──
  lines.push('    class Tasks:')
  if (state.tasks.length === 0) {
    lines.push('        ...  # No tasks recorded yet')
  } else {
    const inProgress = state.tasks.filter(t => t.status === 'in_progress' || t.status === 'planned')
    const done = state.tasks.filter(t => t.status === 'done')
    const blocked = state.tasks.filter(t => t.status === 'blocked')

    if (done.length > 0) {
      lines.push('        completed = [')
      for (const t of done) {
        lines.push(`            ${pyStr(t.description)},`)
      }
      lines.push('        ]')
    }

    if (inProgress.length > 0) {
      lines.push('        pending = [')
      for (const t of inProgress) {
        lines.push(`            ${pyStr(t.description)},`)
      }
      lines.push('        ]')
    }

    if (blocked.length > 0) {
      lines.push('        blocked = [')
      for (const t of blocked) {
        lines.push(`            ${pyStr(t.description)},`)
      }
      lines.push('        ]')
    }
  }
  lines.push('')

  // ── Navigation helper ──
  lines.push('def get_context() -> CurrentSession:')
  lines.push('    """Return the current session state for injection into Context."""')
  lines.push('    return CurrentSession')
  lines.push('')

  return lines.join('\n')
}

// ── Helpers ────────────────────────────────────────────────────────────────

function toPythonVarName(s: string): string {
  let v = s.replace(/[^a-zA-Z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '')
  if (/^\d/.test(v)) v = `_${v}`
  return (v.toLowerCase().slice(0, 40) || 'unknown')
}
