/**
 * Session state serializer and merger for the Context Compression Engine.
 *
 * - mergeExtractionResult: incrementally updates a SessionState from extracted atoms (@deprecated)
 * - serializeToPython: renders the SessionState as a Python file (session_state.py) (@deprecated)
 * - StateSerializer: new class-based serializer with sectioned output
 * - deserializeFromPython: (optional) rehydrates state from the Python output
 */

import {
  type Decision,
  DecisionStatus,
  type Constraint,
  type TaskRecord,
  type SessionState,
  type KnowledgeFact,
  type CodeAnchor,
  type ErrorMemory,
} from './models.js'
import type { ExtractionResult } from './extractors.js'
import { StateMerger } from './merger.js'
import { toVarName, escape, atomicWrite } from './utils.js'

// ── Defaults ───────────────────────────────────────────────────────────────

const MAX_DECISIONS = 30
const MAX_CONSTRAINTS = 20
const MAX_TASKS = 15
const MAX_CODE_ANCHORS = 20
const MAX_ERROR_MEMORIES = 10

export function createEmptySessionState(): SessionState {
  return {
    primaryGoal: '',
    decisions: [],
    constraints: [],
    tasks: [],
    lastUpdatedTurn: 0,
  }
}

// ── Legacy Merger (backward compatibility) ─────────────────────────────────

/**
 * @deprecated Use StateMerger.merge() instead.
 * Kept for backward compatibility.
 */
export function mergeExtractionResult(
  state: SessionState,
  result: ExtractionResult,
  turn: number,
): SessionState {
  const merger = new StateMerger()
  return merger.merge(state, result, turn)
}

// ── State Serializer ───────────────────────────────────────────────────────

export class StateSerializer {
  serialize(state: SessionState): string {
    const lines: string[] = []

    // 1. Header
    lines.push('# session_state.py  (auto-generated by context compressor)')
    lines.push('# ════════════════════════════════════════════════════════════════')
    lines.push('# COMPRESSED SESSION STATE')
    lines.push('# This file captures decisions, constraints, and task progress')
    lines.push('# from the conversation. Re-inject into Context on each turn.')
    lines.push(`# Turn: ${state.lastUpdatedTurn}`)
    if (state.totalTurns) lines.push(`# Total turns: ${state.totalTurns}`)
    if (state.rawCharsIngested) lines.push(`# Raw chars ingested: ${state.rawCharsIngested}`)
    if (state.compressedChars) lines.push(`# Compressed chars: ${state.compressedChars}`)
    lines.push('# ════════════════════════════════════════════════════════════════')
    lines.push('from __future__ import annotations')
    lines.push('from typing import Dict, List, Optional')
    lines.push('')
    lines.push('')

    // 2. Goal
    lines.push('class CurrentSession:')
    lines.push(`    primary_goal = ${pyStr(state.primaryGoal || 'Not yet defined')}`)
    if (state.goalStatus) {
      lines.push(`    goal_status = ${pyStr(state.goalStatus)}`)
    }
    if (state.secondaryGoals && state.secondaryGoals.length > 0) {
      lines.push(`    secondary_goals = ${pyList(state.secondaryGoals)}`)
    }
    lines.push(`    last_updated_turn = ${state.lastUpdatedTurn}`)
    lines.push('')

    // 3. ProjectContext
    if (state.projectName || state.projectType || (state.techStack && state.techStack.length > 0)) {
      lines.push('    class ProjectContext:')
      if (state.projectName) lines.push(`        project_name = ${pyStr(state.projectName)}`)
      if (state.projectType) lines.push(`        project_type = ${pyStr(state.projectType)}`)
      if (state.techStack && state.techStack.length > 0) {
        lines.push(`        tech_stack = ${pyList(state.techStack)}`)
      }
      if (state.architectureStyle) lines.push(`        architecture_style = ${pyStr(state.architectureStyle)}`)
      lines.push('')
    }

    // 4. Decisions
    lines.push('    class Decisions:')
    const activeDecisions = state.decisions.filter(d => d.status === DecisionStatus.ACCEPTED)
    const rejectedDecisions = state.decisions.filter(d => d.status === DecisionStatus.REJECTED)
    const proposedDecisions = state.decisions.filter(d => d.status === DecisionStatus.PROPOSED)

    if (activeDecisions.length === 0 && rejectedDecisions.length === 0 && proposedDecisions.length === 0) {
      lines.push('        ...  # No decisions recorded yet')
    } else {
      if (activeDecisions.length > 0) {
        lines.push('        # Accepted:')
        for (const dec of activeDecisions) {
          lines.push(decisionToPythonLine(dec, 8))
        }
      }

      if (rejectedDecisions.length > 0) {
        lines.push('')
        lines.push('        # Rejected:')
        for (const dec of rejectedDecisions) {
          lines.push(decisionToPythonLine(dec, 8))
        }
      }

      if (proposedDecisions.length > 0) {
        lines.push('')
        lines.push('        # Proposed (pending confirmation):')
        for (const dec of proposedDecisions) {
          lines.push(decisionToPythonLine(dec, 8))
        }
      }
    }
    lines.push('')

    // 5. Constraints
    lines.push('    class Constraints:')
    if (state.constraints.length === 0) {
      lines.push('        ...  # No constraints recorded yet')
    } else {
      const hard = state.constraints.filter(c => c.severity === 'hard')
      const soft = state.constraints.filter(c => c.severity === 'soft')

      if (hard.length > 0) {
        lines.push('        # Hard constraints (MUST follow):')
        for (const con of hard) {
          lines.push(constraintToPythonLine(con, 8))
        }
      }

      if (soft.length > 0) {
        lines.push('')
        lines.push('        # Soft constraints (Recommended):')
        for (const con of soft) {
          lines.push(constraintToPythonLine(con, 8))
        }
      }
    }
    lines.push('')

    // 6. Knowledge
    if (state.facts && state.facts.length > 0) {
      lines.push('    class Knowledge:')
      const byCategory = new Map<string, KnowledgeFact[]>()
      for (const f of state.facts) {
        if (!byCategory.has(f.category)) byCategory.set(f.category, [])
        byCategory.get(f.category)!.push(f)
      }
      for (const [category, facts] of byCategory) {
        lines.push(`        # ${category}:`)
        for (const f of facts) {
          lines.push(factToPythonLine(f, 8))
        }
      }
      lines.push('')
    }

    // 7. Tasks
    lines.push('    class Tasks:')
    if (state.tasks.length === 0) {
      lines.push('        ...  # No tasks recorded yet')
    } else {
      const inProgress = state.tasks.filter(t => t.status === 'in_progress' || t.status === 'planned')
      const done = state.tasks.filter(t => t.status === 'done')
      const blocked = state.tasks.filter(t => t.status === 'blocked')

      if (done.length > 0) {
        lines.push('        completed = [')
        for (const t of done) {
          lines.push(`            ${pyStr(t.description)},`)
        }
        lines.push('        ]')
      }

      if (inProgress.length > 0) {
        lines.push('        pending = [')
        for (const t of inProgress) {
          lines.push(`            ${pyStr(t.description)},`)
        }
        lines.push('        ]')
      }

      if (blocked.length > 0) {
        lines.push('        blocked = [')
        for (const t of blocked) {
          lines.push(`            ${pyStr(t.description)},`)
        }
        lines.push('        ]')
      }
    }
    lines.push('')

    // 8. CodeAnchors
    if (state.codeAnchors && state.codeAnchors.length > 0) {
      lines.push('    class CodeAnchors:')
      const priorityOrder = ['created', 'modified', 'read', 'referenced']
      const sorted = [...state.codeAnchors].sort(
        (a, b) => priorityOrder.indexOf(a.action) - priorityOrder.indexOf(b.action),
      )
      for (const anchor of sorted) {
        lines.push(anchorToPythonLine(anchor, 8))
      }
      lines.push('')
    }

    // 9. ErrorMemory
    if (state.errorMemories && state.errorMemories.length > 0) {
      lines.push('    class ErrorMemory:')
      lines.push('        # Failed approaches (do not retry):')
      for (const err of state.errorMemories) {
        lines.push(errorToPythonLine(err, 8))
      }
      lines.push('')
    }

    // 10. Preferences
    if (state.preferences && Object.keys(state.preferences).length > 0) {
      lines.push('    class Preferences:')
      for (const [key, value] of Object.entries(state.preferences)) {
        lines.push(`        ${toVarName(key)} = ${pyStr(value)}`)
      }
      lines.push('')
    }

    // Navigation helper
    lines.push('def get_context() -> CurrentSession:')
    lines.push('    """Return the current session state for injection into Context."""')
    lines.push('    return CurrentSession')
    lines.push('')

    return lines.join('\n')
  }

  serializeHistory(state: SessionState): string {
    const lines: string[] = []
    const entries = buildHistoryEntries(state)

    lines.push('# session_history.py  (auto-generated by context compressor)')
    lines.push('# Compact timeline archive for debugging and session recovery.')
    lines.push('from __future__ import annotations')
    lines.push('')
    lines.push('class SessionHistory:')
    lines.push(`    session_id = ${pyStr(state.sessionId || 'unknown')}`)
    lines.push(`    total_turns = ${state.totalTurns || 0}`)
    lines.push(`    last_updated_turn = ${state.lastUpdatedTurn || 0}`)
    lines.push(`    primary_goal = ${pyStr(state.primaryGoal || 'Not yet defined')}`)
    lines.push('')
    lines.push('    timeline = [')

    if (entries.length === 0) {
      lines.push(`        ${pyStr('turn 0 | no archived events yet')},`)
    } else {
      for (const entry of entries) {
        lines.push(`        ${pyStr(entry)},`)
      }
    }

    lines.push('    ]')
    lines.push('')
    lines.push('def get_history() -> SessionHistory:')
    lines.push('    return SessionHistory')
    lines.push('')

    return lines.join('\n')
  }

  serializeMetrics(state: SessionState): string {
    const lines: string[] = []
    const rawChars = state.rawCharsIngested || 0
    const compressedChars = state.compressedChars || 0
    const compressionRatio =
      compressedChars > 0
        ? Number((rawChars / compressedChars).toFixed(2))
        : 0
    const acceptedDecisions = state.decisions.filter(
      d => d.status === DecisionStatus.ACCEPTED,
    ).length
    const rejectedDecisions = state.decisions.filter(
      d => d.status === DecisionStatus.REJECTED,
    ).length
    const proposedDecisions = state.decisions.filter(
      d => d.status === DecisionStatus.PROPOSED,
    ).length
    const activeConstraints = state.constraints.filter(c => c.isActive).length
    const completedTasks = state.tasks.filter(t => t.status === 'done').length
    const blockedTasks = state.tasks.filter(t => t.status === 'blocked').length

    lines.push('# session_metrics.py  (auto-generated by context compressor)')
    lines.push('# Diagnostic snapshot for context compression quality and coverage.')
    lines.push('from __future__ import annotations')
    lines.push('')
    lines.push('class SessionMetrics:')
    lines.push(`    session_id = ${pyStr(state.sessionId || 'unknown')}`)
    lines.push(`    total_turns = ${state.totalTurns || 0}`)
    lines.push(`    last_updated_turn = ${state.lastUpdatedTurn || 0}`)
    lines.push(`    raw_chars_ingested = ${rawChars}`)
    lines.push(`    compressed_chars = ${compressedChars}`)
    lines.push(`    compression_ratio = ${compressionRatio}`)
    lines.push(`    decisions_total = ${state.decisions.length}`)
    lines.push(`    decisions_accepted = ${acceptedDecisions}`)
    lines.push(`    decisions_rejected = ${rejectedDecisions}`)
    lines.push(`    decisions_proposed = ${proposedDecisions}`)
    lines.push(`    constraints_active = ${activeConstraints}`)
    lines.push(`    tasks_total = ${state.tasks.length}`)
    lines.push(`    tasks_completed = ${completedTasks}`)
    lines.push(`    tasks_blocked = ${blockedTasks}`)
    lines.push(`    facts_total = ${state.facts?.length || 0}`)
    lines.push(`    code_anchors_total = ${state.codeAnchors?.length || 0}`)
    lines.push(`    error_memories_total = ${state.errorMemories?.length || 0}`)
    lines.push('')
    lines.push('def get_metrics() -> SessionMetrics:')
    lines.push('    return SessionMetrics')
    lines.push('')

    return lines.join('\n')
  }

  async save(state: SessionState, outputPath: string): Promise<void> {
    let content = this.serialize(state)
    let compressedChars = content.length

    for (let iteration = 0; iteration < 3; iteration++) {
      if (state.compressedChars === compressedChars) {
        break
      }
      state.compressedChars = compressedChars
      content = this.serialize(state)
      compressedChars = content.length
    }

    state.compressedChars = compressedChars
    await atomicWrite(outputPath, content)
  }

  async saveHistory(state: SessionState, outputPath: string): Promise<void> {
    await atomicWrite(outputPath, this.serializeHistory(state))
  }

  async saveMetrics(state: SessionState, outputPath: string): Promise<void> {
    await atomicWrite(outputPath, this.serializeMetrics(state))
  }
}

// ── Serialization functions ────────────────────────────────────────────────

export function decisionToPythonLine(d: Decision, indent: number = 8): string {
  const padding = ' '.repeat(indent)
  const varName = toVarName(d.topic)
  const comment = d.alternativesRejected.length > 0
    ? `  # rejected: ${d.alternativesRejected.join(', ')}`
    : ''
  return `${padding}${varName} = ${pyStr(d.choice)}${comment}`
}

export function constraintToPythonLine(c: Constraint, indent: number = 8): string {
  const padding = ' '.repeat(indent)
  const varName = toVarName(`${c.category}_${c.id.slice(-6)}`)
  const severity = c.severity === 'hard' ? '# MUST follow' : '# Recommended'
  return `${padding}${varName} = ${pyStr(c.rule)}  ${severity}`
}

export function factToPythonLine(f: KnowledgeFact, indent: number = 8): string {
  const padding = ' '.repeat(indent)
  const varName = toVarName(`${f.key}_${f.category}`)
  return `${padding}${varName} = ${pyStr(f.value)}`
}

function anchorVarName(filePath: string): string {
  const baseName = filePath.split('/').pop() || filePath
  const stem = baseName.replace(/\.[^.]+$/, '') || baseName
  let hash = 0
  for (let i = 0; i < filePath.length; i++) {
    hash = ((hash << 5) - hash) + filePath.charCodeAt(i)
    hash |= 0
  }
  return `${toVarName(stem)}_${Math.abs(hash).toString(36).slice(0, 6)}`
}

export function anchorToPythonLine(a: CodeAnchor, indent: number = 8): string {
  const padding = ' '.repeat(indent)
  const varName = anchorVarName(a.filePath)
  const loc = a.lineStart > 0 ? `:${a.lineStart}` : ''
  return `${padding}${varName} = ${pyStr(`${a.filePath}${loc} (${a.action})`)}`
}

export function errorToPythonLine(e: ErrorMemory, indent: number = 8): string {
  const padding = ' '.repeat(indent)
  const varName = toVarName(`failed_${e.approach.slice(0, 20)}`)
  return `${padding}${varName} = ${pyStr(e.approach)}  # reason: ${escape(e.failureReason)}`
}

export function taskToPythonBlock(t: TaskRecord, indent: number = 8): string[] {
  const padding = ' '.repeat(indent)
  const lines: string[] = []
  lines.push(`${padding}# Task: ${escape(t.description)} [${t.status}]`)
  if (t.completedSubtasks.length > 0) {
    lines.push(`${padding}completed_subtasks = ${pyList(t.completedSubtasks)}`)
  }
  if (t.remainingSubtasks.length > 0) {
    lines.push(`${padding}remaining_subtasks = ${pyList(t.remainingSubtasks)}`)
  }
  return lines
}

// ── Legacy Python Serializer (backward compatibility) ──────────────────────

function pyStr(value: string): string {
  const escaped = value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `'${escaped}'`
}

function pyList(items: string[]): string {
  if (items.length === 0) return '[]'
  const quoted = items.map(i => pyStr(i))
  return `[${quoted.join(', ')}]`
}

/**
 * @deprecated Use StateSerializer.serialize() instead.
 * Kept for backward compatibility.
 */
export function serializeToPython(state: SessionState): string {
  const serializer = new StateSerializer()
  return serializer.serialize(state)
}

export function serializeHistoryToPython(state: SessionState): string {
  const serializer = new StateSerializer()
  return serializer.serializeHistory(state)
}

export function serializeMetricsToPython(state: SessionState): string {
  const serializer = new StateSerializer()
  return serializer.serializeMetrics(state)
}

function buildHistoryEntries(state: SessionState): string[] {
  const entries: Array<{ turn: number; text: string }> = []

  for (const decision of state.decisions) {
    entries.push({
      turn: decision.turn,
      text: `turn ${decision.turn} | decision:${decision.status} | ${decision.topic} -> ${decision.choice}`,
    })
  }

  for (const constraint of state.constraints) {
    entries.push({
      turn: constraint.turn,
      text: `turn ${constraint.turn} | constraint:${constraint.severity} | ${constraint.rule}`,
    })
  }

  for (const task of state.tasks) {
    entries.push({
      turn: task.turn,
      text: `turn ${task.turn} | task:${task.status} | ${task.description}`,
    })
  }

  for (const fact of state.facts || []) {
    entries.push({
      turn: fact.sourceTurn,
      text: `turn ${fact.sourceTurn} | fact:${fact.category} | ${fact.key}=${fact.value}`,
    })
  }

  for (const anchor of state.codeAnchors || []) {
    entries.push({
      turn: anchor.turn,
      text: `turn ${anchor.turn} | anchor:${anchor.action} | ${anchor.filePath}`,
    })
  }

  for (const error of state.errorMemories || []) {
    entries.push({
      turn: error.turn,
      text: `turn ${error.turn} | error | ${error.approach} -> ${error.failureReason}`,
    })
  }

  return entries
    .sort((a, b) => a.turn - b.turn || a.text.localeCompare(b.text))
    .map(entry => escape(entry.text))
}
